apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: wordpress
    helm:
      values: |
        wordpressUsername: "admin"
        wordpressPassword: "password"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.18
  syncPolicy:
    automated:
      prune: true
      selfHeal: true